// react-ticket-management-app/src/pages/TicketManagement.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Header } from '../components/layout/Header';
import { Footer } from '../components/layout/Footer';
import { TicketCard } from '../components/tickets/TicketCard';
import { TicketForm } from '../components/tickets/TicketForm';
import { Button } from '../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../components/ui/alert-dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { getSession } from '../lib/auth';
import { apiGetTickets, apiCreateTicket, apiUpdateTicket, apiDeleteTicket } from '../lib/mockApi';
import type { Ticket, TicketStatus } from '../lib/storage';
import { toast } from 'sonner';
import { Plus, Filter } from 'lucide-react';

export function TicketManagement() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [filteredTickets, setFilteredTickets] = useState<Ticket[]>([]);
  const [filterStatus, setFilterStatus] = useState<string>(searchParams.get('status') || 'all');
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [selectedTicket, setSelectedTicket] = useState<Ticket | null>(null);
  const [ticketToDelete, setTicketToDelete] = useState<Ticket | null>(null);

  useEffect(() => {
    const session = getSession();
    
    if (!session) {
      toast.error('Your session has expired — please log in again.');
      navigate('/auth/login');
      return;
    }

    loadTickets();
    
    // Handle query parameters
    if (searchParams.get('new') === 'true') {
      setIsFormOpen(true);
    }
  }, [navigate, searchParams]);

  useEffect(() => {
    if (filterStatus === 'all') {
      setFilteredTickets(tickets);
    } else {
      setFilteredTickets(tickets.filter(t => t.status === filterStatus));
    }
  }, [filterStatus, tickets]);

  const loadTickets = () => {
    const session = getSession();
    if (!session) return;
    
    try {
      apiGetTickets().then((res) => {
        if (res.ok && Array.isArray(res.data)) setTickets(res.data as unknown as Ticket[]);
        else if (res.error === 'Unauthorized' || res.error === 'Token expired') {
          toast.error('Your session has expired — please log in again.');
          navigate('/auth/login');
        } else {
          toast.error('Failed to load tickets. Please retry.');
        }
      });
    } catch {
      toast.error('Failed to load tickets. Please retry.');
    }
  };

  const handleCreateTicket = (data: {
    title: string;
    description: string;
    status: TicketStatus;
    priority: 'low' | 'medium' | 'high';
  }) => {
    const session = getSession();
    if (!session) return;

    try {
      apiCreateTicket(data).then((res) => {
        if (res.ok) {
          loadTickets();
          setIsFormOpen(false);
          toast.success('Ticket created successfully!');
        } else {
          if (res.error === 'Unauthorized' || res.error === 'Token expired') {
            toast.error('Your session has expired — please log in again.');
            navigate('/auth/login');
          } else {
            toast.error('Failed to create ticket. Please try again.');
          }
        }
      });
    } catch {
      toast.error('Failed to create ticket. Please try again.');
    }
  };

  const handleUpdateTicket = (data: {
    title: string;
    description: string;
    status: TicketStatus;
    priority: 'low' | 'medium' | 'high';
  }) => {
    const session = getSession();
    if (!session || !selectedTicket) return;

    try {
  apiUpdateTicket(selectedTicket.id, data).then((res) => {
        if (res.ok) {
          loadTickets();
          setIsFormOpen(false);
          setSelectedTicket(null);
          toast.success('Ticket updated successfully!');
        } else {
          if (res.error === 'Unauthorized' || res.error === 'Token expired') {
            toast.error('Your session has expired — please log in again.');
            navigate('/auth/login');
          } else {
            toast.error('Failed to update ticket. Please try again.');
          }
        }
      });
    } catch {
      toast.error('Failed to update ticket. Please try again.');
    }
  };

  const handleEditClick = (ticket: Ticket) => {
    setSelectedTicket(ticket);
    setIsFormOpen(true);
  };

  const handleDeleteClick = (ticket: Ticket) => {
    setTicketToDelete(ticket);
    setIsDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    const session = getSession();
    if (!session || !ticketToDelete) return;

    try {
  apiDeleteTicket(ticketToDelete.id).then((res) => {
        if (res.ok && res.data) {
          loadTickets();
          toast.success('Ticket deleted successfully!');
        } else {
          if (res.error === 'Unauthorized' || res.error === 'Token expired') {
            toast.error('Your session has expired — please log in again.');
            navigate('/auth/login');
          } else {
            toast.error('Failed to delete ticket. Please try again.');
          }
        }
      });
    } catch {
      toast.error('Failed to delete ticket. Please try again.');
    } finally {
      setIsDeleteDialogOpen(false);
      setTicketToDelete(null);
    }
  };

  const handleFormCancel = () => {
    setIsFormOpen(false);
    setSelectedTicket(null);
  };

  const session = getSession();
  
  if (!session) {
    return null;
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 bg-slate-50 py-8">
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
            <div>
              <h1 className="mb-2">Ticket Management</h1>
              <p className="text-slate-600">
                Create, view, edit, and manage your support tickets
              </p>
            </div>
            <Button onClick={() => {
              setSelectedTicket(null);
              setIsFormOpen(true);
            }}>
              <Plus className="w-4 h-4 mr-2" />
              New Ticket
            </Button>
          </div>

          {/* Filter */}
          <div className="mb-6 flex items-center gap-3">
            <Filter className="w-5 h-5 text-slate-500" />
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-[200px]">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Tickets</SelectItem>
                <SelectItem value="open">Open</SelectItem>
                <SelectItem value="in_progress">In Progress</SelectItem>
                <SelectItem value="closed">Closed</SelectItem>
              </SelectContent>
            </Select>
            <span className="text-sm text-slate-600">
              Showing {filteredTickets.length} ticket{filteredTickets.length !== 1 ? 's' : ''}
            </span>
          </div>

          {/* Tickets Grid */}
          {filteredTickets.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-slate-600 mb-4">
                {filterStatus === 'all' 
                  ? 'No tickets yet. Create your first ticket to get started!' 
                  : `No ${filterStatus.replace('_', ' ')} tickets found.`}
              </p>
              {filterStatus === 'all' && (
                <Button onClick={() => {
                  setSelectedTicket(null);
                  setIsFormOpen(true);
                }}>
                  <Plus className="w-4 h-4 mr-2" />
                  Create First Ticket
                </Button>
              )}
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredTickets.map((ticket) => (
                <TicketCard
                  key={ticket.id}
                  ticket={ticket}
                  onEdit={handleEditClick}
                  onDelete={handleDeleteClick}
                />
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Create/Edit Dialog */}
      <Dialog open={isFormOpen} onOpenChange={(open) => {
        if (!open) handleFormCancel();
      }}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle>
              {selectedTicket ? 'Edit Ticket' : 'Create New Ticket'}
            </DialogTitle>
            <DialogDescription>
              {selectedTicket 
                ? 'Update the ticket details below.' 
                : 'Fill in the details to create a new ticket.'}
            </DialogDescription>
          </DialogHeader>
          <TicketForm
            ticket={selectedTicket}
            onSubmit={selectedTicket ? handleUpdateTicket : handleCreateTicket}
            onCancel={handleFormCancel}
          />
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={isDeleteDialogOpen} onOpenChange={(open) => {
        setIsDeleteDialogOpen(open);
        if (!open) setTicketToDelete(null);
      }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete the ticket "{ticketToDelete?.title}".
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className='flex-1'>
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDelete}
              className="flex-1 bg-red-600 hover:bg-red-700"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Footer />
    </div>
  );
}

// vue-ticket-management-app/src/views/TicketManagement.vue
<template>
  <div class="min-h-screen flex flex-col">
    <main class="flex-1 bg-slate-50 py-8">
      <div class="max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
          <div>
            <h1 class="mb-2">Ticket Management</h1>
            <p class="text-slate-600">
              Create, view, edit, and manage your support tickets
            </p>
          </div>
          <Button @click="openCreateForm">
            <Plus class="w-4 h-4 mr-2" />
            New Ticket
          </Button>
        </div>

        <!-- Filter -->
        <div class="mb-6 flex items-center gap-3">
          <Filter class="w-5 h-5 text-slate-500" />
          <Select v-model="filterStatus" :options="filterOptions" class="w-[200px]" />
          <span class="text-sm text-slate-600">
            Showing {{ filteredTickets.length }} ticket{{ filteredTickets.length !== 1 ? 's' : '' }}
          </span>
        </div>

        <!-- Tickets Grid -->
        <div v-if="filteredTickets.length === 0" class="text-center py-12">
          <p class="text-slate-600 mb-4">
            {{ filterStatus === 'all'
               ? 'No tickets yet. Create your first ticket to get started!'
               : `No ${filterStatus.replace('_', ' ')} tickets found.` }}
          </p>
          <Button v-if="filterStatus === 'all'" @click="openCreateForm">
            <Plus class="w-4 h-4 mr-2" />
            Create First Ticket
          </Button>
        </div>
        <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <TicketCard
            v-for="ticket in filteredTickets"
            :key="ticket.id"
            :ticket="ticket"
            @edit="handleEdit"
            @delete="handleDelete"
          />
        </div>
      </div>
    </main>

    <!-- Create/Edit Dialog -->
    <Dialog :open="isFormOpen" @close="closeForm">
      <DialogContent class="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>
            {{ selectedTicket ? 'Edit Ticket' : 'Create New Ticket' }}
          </DialogTitle>
          <DialogDescription>
            {{ selectedTicket
               ? 'Update the ticket details below.'
               : 'Fill in the details to create a new ticket.' }}
          </DialogDescription>
        </DialogHeader>
        <TicketForm
           :ticket="selectedTicket"
           @submit="handleFormSubmit"
           @cancel="closeForm"
         />
      </DialogContent>
    </Dialog>

    <!-- Delete Confirmation Dialog -->
    <Dialog :open="isDeleteDialogOpen" @close="cancelDelete">
      <DialogContent >
        <DialogHeader>
          <DialogTitle>Are you sure?</DialogTitle>
          <DialogDescription>
            This will permanently delete the ticket "{{ ticketToDelete?.title }}".
            This action cannot be undone.
          </DialogDescription>
        </DialogHeader>
        <div class="flex gap-3 pt-4">
          <Button variant="outline" @click="cancelDelete" class="flex-1">
            Cancel
          </Button>
          <Button @click="confirmDelete" variant="destructive" class="flex-1 hover:bg-red-700">
            Delete
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Plus, Filter } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { useAuthStore } from '../stores/auth'
import { apiGetTickets, apiCreateTicket, apiUpdateTicket, apiDeleteTicket } from '../lib/mockApi'
import type { Ticket } from '../lib/types'
import Button from '../components/ui/Button.vue'
import Select from '../components/ui/Select.vue'
import Dialog from '../components/ui/Dialog.vue'
import DialogContent from '../components/ui/DialogContent.vue'
import DialogHeader from '../components/ui/DialogHeader.vue'
import DialogTitle from '../components/ui/DialogTitle.vue'
import DialogDescription from '../components/ui/DialogDescription.vue'
import TicketCard from '../components/tickets/TicketCard.vue'
import TicketForm from '../components/tickets/TicketForm.vue'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()

const tickets = ref<Ticket[]>([])
const filterStatus = ref(route.query.status as string || 'all')
const isFormOpen = ref(false)
const isDeleteDialogOpen = ref(false)
const selectedTicket = ref<Ticket | null>(null)
const ticketToDelete = ref<Ticket | null>(null)

const filterOptions = [
  { value: 'all', label: 'All Tickets' },
  { value: 'open', label: 'Open' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'closed', label: 'Closed' }
]

const filteredTickets = computed(() => {
  if (filterStatus.value === 'all') {
    return tickets.value
  }
  return tickets.value.filter(t => t.status === filterStatus.value)
})

const loadTickets = async () => {
  if (!authStore.isAuthenticated) return

  try {
    const res = await apiGetTickets()
    if (res.ok && Array.isArray(res.data)) {
      tickets.value = res.data as unknown as Ticket[]
    } else if (res.error === 'Unauthorized' || res.error === 'Token expired') {
      authStore.logout()
      router.push('/auth/login')
    }
  } catch (e) {
    console.error('Failed to load tickets:', e)
  }
}

const openCreateForm = () => {
  selectedTicket.value = null
  isFormOpen.value = true
}

const closeForm = () => {
  isFormOpen.value = false
  selectedTicket.value = null
}

const handleCreate = async (data: { title: string; description: string; status: 'open' | 'in_progress' | 'closed'; priority: string }) => {
  try {
    const res = await apiCreateTicket(data)
    if (res.ok) {
      await loadTickets()
      closeForm()
      toast.success('Ticket created successfully!')
    } else if (res.error === 'Unauthorized' || res.error === 'Token expired') {
      authStore.logout()
      router.push('/auth/login')
    } else {
      toast.error(res.error || 'Failed to create ticket')
    }
  } catch (e) {
    console.error('Failed to create ticket:', e)
    toast.error('Failed to create ticket')
  }
}

const handleEdit = (ticket: Ticket) => {
  selectedTicket.value = ticket
  isFormOpen.value = true
}

const handleFormSubmit = async (data: { title: string; description: string; status: 'open' | 'in_progress' | 'closed'; priority: string }) => {
  if (selectedTicket.value) {
    await handleUpdate(data)
  } else {
    await handleCreate(data)
  }
}

const handleUpdate = async (data: { title: string; description: string; status: 'open' | 'in_progress' | 'closed'; priority: string }) => {
  if (!selectedTicket.value) return

  console.log('Updating ticket:', selectedTicket.value.id, 'with data:', data)

  try {
    const res = await apiUpdateTicket(selectedTicket.value.id, data)
    console.log('Update response:', res)
    if (res.ok) {
      await loadTickets()
      closeForm()
      toast.success('Ticket updated successfully!')
    } else if (res.error === 'Unauthorized' || res.error === 'Token expired') {
      authStore.logout()
      router.push('/auth/login')
    } else {
      toast.error(res.error || 'Failed to update ticket')
    }
  } catch (e) {
    console.error('Failed to update ticket:', e)
    toast.error('Failed to update ticket')
  }
}

const handleDelete = (ticket: Ticket) => {
  ticketToDelete.value = ticket
  isDeleteDialogOpen.value = true
}

const confirmDelete = async () => {
  if (!ticketToDelete.value) return

  try {
    const res = await apiDeleteTicket(ticketToDelete.value.id)
    if (res.ok && res.data) {
      await loadTickets()
      toast.success('Ticket deleted successfully!')
    } else if (res.error === 'Unauthorized' || res.error === 'Token expired') {
      authStore.logout()
      router.push('/auth/login')
    } else {
      toast.error(res.error || 'Failed to delete ticket')
    }
  } catch (e) {
    console.error('Failed to delete ticket:', e)
    toast.error('Failed to delete ticket')
  } finally {
    cancelDelete()
  }
}

const cancelDelete = () => {
  isDeleteDialogOpen.value = false
  ticketToDelete.value = null
}

watch(() => route.query.new, (newVal) => {
  if (newVal === 'true') {
    openCreateForm()
  }
})

onMounted(() => {
  loadTickets()

  // Handle query parameters
  if (route.query.new === 'true') {
    openCreateForm()
  }
})
</script>
